/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['introduction'],
    // },
    {
      type: 'doc',
      id: 'introduction', // document ID
      label: 'Introduction', // sidebar label
    },
    {
      type: 'doc',
      id: 'understand', // document ID
      label: 'Understand', // sidebar label
    },
    {
      type: 'doc',
      id: 'quickstart', // document ID
      label: 'Quickstart', // sidebar label
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'doc',
          id: 'guides/authentication'
        },
        {
          type: 'category',
          label: 'Uploading Videos',
          link: {
            type: 'doc',
            id: 'guides/uploading-videos/overview',
          },
          items: [
            'guides/uploading-videos/upload-from-the-local-file-system',
            `guides/uploading-videos/upload-from-a-url`,
            {
              type: 'category',
              label: 'Cloud-to-Cloud Transfers',
              link: {
                type: 'doc',
                id: 'guides/uploading-videos/cloud-to-cloud-transfers/overview'
              },
              items: [
                'guides/uploading-videos/cloud-to-cloud-transfers/set-up-an-integration',
                'guides/uploading-videos/cloud-to-cloud-transfers/download-and-edit-the-list-of-videos',
                'guides/uploading-videos/cloud-to-cloud-transfers/transfer-and-index-videos',
                {
                  type: 'category',
                  label: 'Manage Integrations',
                  link: {
                    type: 'doc',
                    id: 'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/overview'
                  },
                  items: [
                    'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/view-statistics',
                    'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/synchronize-data',
                    'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/remove-an-integration'
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/engines',
        'api-reference/indexes'
      ]
    },
  ],
};

module.exports = sidebars;
