/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['introduction'],
    // },
    {
      type: 'doc',
      id: 'introduction', // document ID
      label: 'Introduction', // sidebar label
    },
    {
      type: 'doc',
      id: 'understand', // document ID
      label: 'Understand', // sidebar label
    },
    {
      type: 'doc',
      id: 'quickstart', // document ID
      label: 'Quickstart', // sidebar label
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'doc',
          id: 'guides/authentication'
        },
        {
          type: 'category',
          label: 'Uploading Videos',
          link: {
            type: 'doc',
            id: 'guides/uploading-videos/overview',
          },
          items: [
            'guides/uploading-videos/upload-from-the-local-file-system',
            `guides/uploading-videos/upload-from-a-url`,
            {
              type: 'category',
              label: 'Cloud-to-Cloud Transfers',
              link: {
                type: 'doc',
                id: 'guides/uploading-videos/cloud-to-cloud-transfers/overview'
              },
              items: [
                'guides/uploading-videos/cloud-to-cloud-transfers/set-up-an-integration',
                'guides/uploading-videos/cloud-to-cloud-transfers/download-and-edit-the-list-of-videos',
                'guides/uploading-videos/cloud-to-cloud-transfers/transfer-and-index-videos',
                {
                  type: 'category',
                  label: 'Manage Integrations',
                  link: {
                    type: 'doc',
                    id: 'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/overview'
                  },
                  items: [
                    'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/view-statistics',
                    'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/synchronize-data',
                    'guides/uploading-videos/cloud-to-cloud-transfers/manage-integrations/remove-an-integration'
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Performing Searches',
          link: {
            type: 'doc',
            id: 'guides/performing-searches/overview'
          },
          items: [
            'guides/performing-searches/single-search-option',
            'guides/performing-searches/multiple-search-options'
          ]
        },
        {
          type: 'category',
          label: 'Providing Your Custom Transcriptions',
          link: {
            type: 'doc',
            id: 'guides/providing-your-custom-transcriptions/overview'
          },
          items: [
            'guides/providing-your-custom-transcriptions/local-file-system',
            'guides/providing-your-custom-transcriptions/urls',
            'guides/providing-your-custom-transcriptions/cloud-to-cloud'
          ],
        },
        {
          type: 'category',
          label: 'Extracting Information from Videos',
          link: {
            type: 'doc',
            id: 'guides/extracting-information-from-videos/overview'
          },
          items: [
            'guides/extracting-information-from-videos/transcriptions',
            'guides/extracting-information-from-videos/text-in-video'
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/search-engines',
        'concepts/indexing-options',
        'concepts/search-options',
        {
          type: 'category',
          label: 'Pagination',
          link: {
            type: 'doc',
            id: 'concepts/pagination/overview'
          },
          items: [
            'concepts/pagination/indexes',
            'concepts/pagination/search'
          ]
        },
        'concepts/sorting',
        {
          type: `category`,
          label: 'Filtering',
          link: {
            type: 'doc',
            id: 'concepts/filtering/overview'
          },
          items: [
            'concepts/filtering/indexes',
            'concepts/filtering/metadata'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'api-reference/overview'
      },
      items: [
        'api-reference/engines',
        'api-reference/indexes',
        'api-reference/indexes-tasks',
        'api-reference/indexes-tasks-transfers',
        'api-reference/indexes-videos',
        'api-reference/search',
        'api-reference/error-codes'
      ]
    },
    'faq',
    'api-changelog',
    'roadmap'
  ],
};

module.exports = sidebars;
