swagger: "2.0"
host: 35.82.130.225:8080 
basePath: /v1
accepts:
  - application/json
produces:
  - application/json
servers:
  - url: http://35.82.130.225:8080 
paths:
  /engines:
    get:
      summary: List search engines
      description: List all the search engines that are available in your account.
      operationId: listEngines
      tags:
        - Engines 
      parameters:
        - name: x-api-key
          in: header
          description: >
            Your API key.

            **NOTE:** You can find your API key on the [Dashboard](https://api.twelvelabs.io/dashboard) page.   
          required: true
          type: string 
        - name: Content-Type
          in: header
          description: Must be set to `application/json`.
      responses:
        '200':
          description: The search engines have successfully been retrieved.
          content:
            application/json:
              schema:
                type: Object 
                properties:
                  id:
                  type: integer
  /engines/{engine-id}:
    get:
      summary: Retrieve a search engine
      operationId: retrieveSearchEngine
      tags:
        - Engines
      parameters:
        - $ref: '#/components/parameters/x-api-key' 
        - $ref: '#/components/parameters/Content-Type' 
        - name: engine-id
          in: path
          description: The identifier of the engine to retrieve.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The specified engine has successfully been retrieved.
  /indexes:
    post:
      summary: Create an index.
      operationId: createIndex
      tags:
        - Indexes
      parameters:
        - $ref: '#/components/parameters/x-api-key' 
        - $ref: '#/components/parameters/Content-Type' 
        - name: engine-id
          in: body
          description: >
            Specifies the search engine. The following options are available:
              - `marengo2`
              - `marengo`
          required: true
          schema:
            type: string
            example: marengo2
      responses:
        '200':
          description: The specified engine has successfully been retrieved.
components:
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      description: Must be set to `application/json`.
      type: string
      required: true
    x-api-key:
      name: x-api-key
      in: header
      description: >
        Your API key.

        **NOTE:** You can find your API key on the [Dashboard](https://api.twelvelabs.io/dashboard) page.
      type: string
      required: true 
